[tool.poetry]
name = "pinecone-text"
version = "0.1.0"
description = ""
authors = ["Amnon Catav <catav.amnon1@gmail.com>"]
readme = "README.md"
packages = [{include = "pinecone_text"}]

[tool.poetry.dependencies]
python = "^3.8"
scikit-learn = "^1.2.1"
torch = "^1.13.1"
transformers = "^4.26.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
mypy = "^1.0.1"
black = "^23.1.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
